cam_right_wrist:
  camera:
    ros__parameters:
      # serial_no: "235123071335"
      serial_no: "332522071763"
      rgb_camera:
        enable_auto_exposure: false
      depth_module:
        color_profile: '640,480,60'
        enable_auto_exposure: false
      enable_color: true
      enable_depth: false
      enable_infra: false
      enable_infra1: false
      enable_infra2: false

cam_left_wrist:
  camera:
    ros__parameters:
      # serial_no: "235123072997"
      serial_no: "332522071763"
      rgb_camera:
        enable_auto_exposure: false
      depth_module:
        color_profile: '640,480,60'
        enable_auto_exposure: false
      enable_color: true
      enable_depth: false
      enable_infra: false
      enable_infra1: false
      enable_infra2: false